### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by arguiot** [lukalafaye/Project-Euler#2]
I have solutions up to level 50 (and more I think), but I don't have the code (I never saved this work 😢), are you interested?

**Comment by arguiot** [comment]
Any activity here? @lukalafaye

**Comment by lukalafaye** [comment]
Yeah that would be great, you can make a PR for the README.md with the solutions!

**Comment by arguiot** [comment]
Ok, I will do that.

P.S. Have you starred my new hot project: https://github.com/arguiot/TheoremJS ?

**Comment by arguiot** [comment]
Done, you can review my PR: #3
